### ISSUE TITLE
[Bug]: `monitor reset halt` command fails for LPCXpresso55S69 if using CMSIS Pack support in pyOCD

### ISSUE THREAD

**Issue by jreineckearm** [Open-CMSIS-Pack/vscode-cmsis-debugger#92]
### Summary

As the title says

### Description

Issuing a `monitor reset halt` command for pyOCD (for example as part of `initCommands`) while debugging an NXP LPC55S69 device (e.g. on LPCXpresso55S69) causes an error:
```
monitor reset halt
0007776 E Error while running debug sequence 'ResetSystem' (core cm33_core0): Memory transfer fault [pack_target]
0007776 E Transfer failure while executing remote command 'reset halt': Memory transfer fault [gdbserver]
Resetting target with halt
Transfer failed: Memory transfer fault
```
This problem goes away when you fall back to the pyOCD built-in support for the LPC55S69.

### Steps to Reproduce

1. Build and set up a debug session for the LPCXpresso55S69, Arm CMSIS Debugger, and pyOCD.
2. Prepend `monitor reset halt` to the default config's `initCommands` list.
3. Make sure you use CMSIS Pack debug resources (use a `cbuild-run` file or add the corresponding pyocd CLI args).
4. Try to connect.
5. Above mentioned error shows.

### Expected Behavior

A System Reset succeeds without error messages, or suppresses expected error messages (for example due to an too early poll of a status register).

**Comment by TeoMahnic** [comment]
Fixed with improved connection robustness and updated handling of `__errorcontrol` and `__ap` variables in debug sequences.

Addressed in pyOCD: [v0.0.0-standalone-cbuild5](https://github.com/MatthiasHertel80/pyOCD/releases/tag/v0.0.0-standalone-cbuild5)

Because LPC55S69 is a multi-core device the `cbuild-run.yml` file needs to contain the following description (if not yet generated by the CMSIS-Toolbox) for connection, flash programming and running the debug sequences:

```yml
  debug-topology:
    debugports:
      - dpid: 0
        accessports:
          - apid: 0
            index: 0
          - apid: 1
            index: 1
    processors:
      - pname: cm33_core0
        apid: 0
      - pname: cm33_core1
        apid: 1
```
